export const FETCH_ALL_SERIES_REQUEST = 'FETCH_ALL_SERIES_REQUEST';
export const FETCH_ALL_SERIES_SUCCESS = 'FETCH_ALL_SERIES_SUCCESS';
export const FETCH_ALL_SERIES_FAILURE = 'FETCH_ALL_SERIES_FAILURE';

export const RESET_SERIES = 'RESET_SERIES';

