export const FETCH_ALL_TOP_IMDB_REQUEST = 'FETCH_ALL_TOP_IMDB_REQUEST';
export const FETCH_ALL_TOP_IMDB_SUCCESS = 'FETCH_ALL_TOP_IMDB_SUCCESS';
export const FETCH_ALL_TOP_IMDB_FAILURE = 'FETCH_ALL_TOP_IMDB_FAILURE';

export const RESET_TOP_IMDB = 'RESET_TOP_IMDB';

